apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uimnfij35-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uimnfij35-python 
  name: uimnfij35-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: uimnfij35-python 
